import { json, type LoaderFunctionArgs, type MetaFunction } from '@remix-run/cloudflare';
import { useLoaderData } from '@remix-run/react';
import examplePageSpec from '@ithinq-pagespec/page-spec.example.json';
import type { PageSpec } from '@ithinq-pagespec/page-spec';
import { buildImagePrompt, orchestrateCreative } from '~/lib/ithinq/creative-ai';
import { MED_SPA_DEMO_INSTRUCTION, readCreativeRequest } from '~/lib/ithinq/creative-ai/route-input';

export const meta: MetaFunction = () => [
  { title: 'iThinq creative lab' },
  { name: 'description', content: 'Plain-language request to generated creative page' },
];

const PRESETS = [
  { label: 'Med Spa · premium', instruction: MED_SPA_DEMO_INSTRUCTION },
  {
    label: 'HVAC · bold direct response',
    instruction:
      'Create a bold direct-response page for HVAC companies that are losing leads because calls go unanswered.',
  },
  {
    label: 'Typography-first',
    instruction: 'Create a minimal, typographic page with no images. Understated and premium.',
  },
];

export async function loader({ request, context }: LoaderFunctionArgs) {
  const input = readCreativeRequest(request);
  const spec = examplePageSpec as unknown as PageSpec;
  const env = (context?.cloudflare?.env ?? {}) as unknown as Record<string, string | undefined>;

  const run = await orchestrateCreative(spec, input, { env });
  const query = new URL(request.url).search;

  return json({
    run: {
      request: run.request,
      strategy: run.strategy,
      needs: run.needs.map((need) => ({ ...need, prompt: buildImagePrompt(need, run.strategy) })),
      assets: run.assets,
      failures: run.failures,
      provider: run.provider,
      model: run.model,
      synthetic: run.synthetic,
    },
    query,
    presets: PRESETS,
  });
}

export default function CreativeLab() {
  const { run, query, presets } = useLoaderData<typeof loader>();

  return (
    <main className="min-h-screen bg-[#0b0f14] text-white p-4 md:p-6 flex flex-col gap-4">
      <header className="rounded-2xl border border-white/10 bg-white/5 px-5 py-4">
        <p className="m-0 text-[11px] uppercase tracking-[0.18em] text-[#7dd3a0] font-bold">
          iThinq creative lab &#183; engineering review surface
        </p>
        <h1 className="m-0 mt-1 text-xl md:text-2xl font-semibold tracking-tight">
          Plain-language request &#8594; generated creative page
        </h1>
        <p className="m-0 mt-2 text-sm text-white/60">&ldquo;{run.request.userInstruction}&rdquo;</p>
        <div className="mt-3 flex flex-wrap gap-2 text-xs">
          {presets.map((preset) => (
            <a
              key={preset.label}
              className="rounded-full border border-white/15 px-3 py-1.5 hover:bg-white/10"
              href={`/ithinq/creative-lab?instruction=${encodeURIComponent(preset.instruction)}`}
            >
              {preset.label}
            </a>
          ))}
        </div>
        {run.synthetic ? (
          <p className="m-0 mt-3 rounded-xl border border-amber-400/40 bg-amber-400/10 px-3 py-2 text-xs text-amber-200">
            <strong>No OpenAI credential configured.</strong> Imagery below is a deterministic development placeholder
            from <code className="font-mono">{run.model}</code> &mdash; it is not AI-generated. Set
            <code className="font-mono"> OPENAI_API_KEY</code> server-side to generate with{' '}
            <code className="font-mono">gpt-image-1</code>.
          </p>
        ) : (
          <p className="m-0 mt-3 rounded-xl border border-[#7dd3a0]/40 bg-[#7dd3a0]/10 px-3 py-2 text-xs text-[#c9f5da]">
            Imagery generated by <code className="font-mono">{run.provider}</code> /{' '}
            <code className="font-mono">{run.model}</code>.
          </p>
        )}
      </header>

      <section className="grid grid-cols-1 xl:grid-cols-[340px_minmax(0,1fr)] gap-4 flex-1 min-h-0">
        <aside className="rounded-2xl border border-white/10 bg-white/5 p-4 text-sm overflow-auto max-h-[calc(100vh-220px)]">
          <h2 className="m-0 text-sm font-semibold">Creative strategy</h2>
          <dl className="mt-3 grid grid-cols-2 gap-2 text-xs">
            {(
              [
                ['Direction', run.strategy.directionId],
                ['Narrative', run.strategy.narrativeAngle],
                ['Mood', run.strategy.visualMood],
                ['Images', run.strategy.imageStrategy],
                ['Density', run.strategy.pageDensity],
                ['CTA', run.strategy.ctaIntensity],
                ['Tone', run.request.tone],
                ['Goal', run.request.conversionGoal],
              ] as const
            ).map(([label, value]) => (
              <div key={label}>
                <dt className="text-white/40">{label}</dt>
                <dd className="m-0 mt-0.5">{value}</dd>
              </div>
            ))}
          </dl>

          <h3 className="mt-5 mb-2 text-xs uppercase tracking-widest text-white/40">Why</h3>
          <ul className="list-none p-0 m-0 space-y-1.5 text-xs text-white/65">
            {run.strategy.rationale.map((line) => (
              <li key={line} className="rounded-lg bg-black/25 px-3 py-2">
                {line}
              </li>
            ))}
          </ul>

          <h3 className="mt-5 mb-2 text-xs uppercase tracking-widest text-white/40">
            Asset needs ({run.needs.length})
          </h3>
          {run.needs.length === 0 ? (
            <p className="text-xs text-white/50 m-0">
              None &mdash; a typography-first strategy correctly requests no imagery.
            </p>
          ) : (
            run.needs.map((need) => {
              const asset = run.assets.find((item) => item.assetNeedId === need.id);

              return (
                <div key={need.id} className="rounded-xl bg-black/25 px-3 py-2 mb-2">
                  <div className="flex items-center justify-between gap-2">
                    <span className="font-mono text-[11px] text-[#7dd3a0]">{need.role}</span>
                    <span className="text-[10px] text-white/40">
                      {need.aspectRatio} &#183; {need.placementIntent}
                    </span>
                  </div>
                  <p className="m-0 mt-1 text-[11px] text-white/60">{need.subject}</p>
                  <details className="mt-1.5">
                    <summary className="cursor-pointer text-[10px] text-white/40">image prompt</summary>
                    <p className="m-0 mt-1 text-[10px] text-white/50 leading-relaxed">{need.prompt}</p>
                  </details>
                  {asset ? (
                    <img
                      src={asset.url}
                      alt={asset.alt}
                      className="mt-2 w-full rounded-lg border border-white/10"
                      loading="lazy"
                    />
                  ) : (
                    <p className="m-0 mt-2 text-[10px] text-amber-300">not generated</p>
                  )}
                </div>
              );
            })
          )}

          {run.failures.length > 0 && (
            <>
              <h3 className="mt-5 mb-2 text-xs uppercase tracking-widest text-amber-300">Failures</h3>
              {run.failures.map((failure) => (
                <p key={failure.needId} className="m-0 mb-1 text-[11px] text-amber-200">
                  <strong>{failure.needId}</strong> ({failure.code}
                  {failure.required ? ', required' : ', optional'}): {failure.detail}
                </p>
              ))}
            </>
          )}
        </aside>

        <div className="rounded-2xl overflow-hidden bg-white border border-white/10 min-h-[760px]">
          <iframe
            title="Generated creative page"
            src={`/ithinq/creative-preview${query}`}
            sandbox="allow-same-origin allow-popups allow-popups-to-escape-sandbox"
            className="block w-full h-[calc(100vh-220px)] min-h-[760px] border-0"
          />
        </div>
      </section>
    </main>
  );
}
