import { resolve } from 'node:path';
import { AssetStoreError, devAssetStore, FileSystemAssetStore, type AssetStore } from './asset-store';
import { S3AssetStore } from './s3-asset-store';

/**
 * Choose where generated bytes live, from the server environment.
 *
 * Deliberately shaped like `resolveGenerator`: one function, read at the edge,
 * so no caller has to know which backend answered. The difference is what
 * happens when configuration is absent — an absent image key degrades to a
 * clearly-marked placeholder, but an absent asset store must NOT degrade
 * silently to ephemeral disk in production, because the symptom is imagery that
 * simply disappears on the next deploy. So partial configuration is a hard
 * error and complete absence is the documented development default.
 */
const S3_KEYS = [
  'RENDERER_ASSET_S3_ENDPOINT',
  'RENDERER_ASSET_S3_BUCKET',
  'RENDERER_ASSET_S3_ACCESS_KEY_ID',
  'RENDERER_ASSET_S3_SECRET_ACCESS_KEY',
] as const;

function read(env: Record<string, string | undefined>, key: string): string | undefined {
  const value = env[key] ?? (typeof process === 'undefined' ? undefined : process.env?.[key]);
  const trimmed = value?.trim();

  return trimmed ? trimmed : undefined;
}

export function resolveAssetStore(env: Record<string, string | undefined> = {}): AssetStore {
  const present = S3_KEYS.filter((key) => read(env, key) !== undefined);

  if (present.length > 0 && present.length < S3_KEYS.length) {
    const missing = S3_KEYS.filter((key) => read(env, key) === undefined);

    /*
     * Names only. The values are credentials and never appear in a diagnostic.
     */
    throw new AssetStoreError(
      `Asset store is partially configured; missing ${missing.join(', ')}.`,
      'incomplete_configuration',
    );
  }

  if (present.length === S3_KEYS.length) {
    return new S3AssetStore({
      endpoint: read(env, 'RENDERER_ASSET_S3_ENDPOINT')!,
      bucket: read(env, 'RENDERER_ASSET_S3_BUCKET')!,

      // R2 and MinIO want `auto`; S3 wants a real region.
      region: read(env, 'RENDERER_ASSET_S3_REGION') ?? 'auto',
      accessKeyId: read(env, 'RENDERER_ASSET_S3_ACCESS_KEY_ID')!,
      secretAccessKey: read(env, 'RENDERER_ASSET_S3_SECRET_ACCESS_KEY')!,
      prefix: read(env, 'RENDERER_ASSET_S3_PREFIX'),
    });
  }

  /*
   * A Render persistent disk is the other durable answer, and it needs no code
   * path of its own: point this at the mount and `FileSystemAssetStore` is
   * already durable across deploys.
   */
  const directory = read(env, 'RENDERER_ASSET_DIR');

  return directory ? new FileSystemAssetStore(resolve(directory)) : devAssetStore;
}
