import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, resolve } from 'node:path';

/**
 * Where generated bytes live between generation and delivery.
 *
 * Deliberately an interface with one development implementation. Generated
 * media must survive a process restart to be reviewable, so the dev backend
 * writes to disk rather than holding bytes in memory — an in-memory map would
 * make the delivery route dead architecture the moment the server reloaded.
 *
 * PRODUCTION SEAM: a deployment replaces `FileSystemAssetStore` with an
 * object-store implementation (R2, S3 or equivalent) behind this same
 * interface. Nothing above this file knows where bytes are kept. Choosing that
 * store is a deployment decision and is deliberately not made here.
 */
export interface StoredAsset {
  id: string;
  mimeType: string;
  bytes: Uint8Array;
}

export interface AssetStore {
  put(id: string, mimeType: string, bytes: Uint8Array): Promise<void>;
  get(id: string): Promise<StoredAsset | null>;

  /** Public path the renderer serves this asset from. */
  urlFor(id: string): string;
}

const EXTENSIONS: Readonly<Record<string, string>> = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/webp': 'webp',
  'image/svg+xml': 'svg',
};

const MIME_BY_EXTENSION: Readonly<Record<string, string>> = {
  png: 'image/png',
  jpg: 'image/jpeg',
  webp: 'image/webp',
  svg: 'image/svg+xml',
};

/** Ids are content-addressed, so identical creative is stored once. */
export function assetIdFor(prompt: string, needId: string): string {
  return createHash('sha256').update(`${needId}\n${prompt}`).digest('hex').slice(0, 32);
}

export class FileSystemAssetStore implements AssetStore {
  constructor(private readonly _root: string = resolve(process.cwd(), '.data/ithinq-generated')) {}

  private _pathFor(id: string, extension: string): string {
    return join(this._root, `${id}.${extension}`);
  }

  async put(id: string, mimeType: string, bytes: Uint8Array): Promise<void> {
    const extension = EXTENSIONS[mimeType] ?? 'bin';
    await mkdir(this._root, { recursive: true });
    await writeFile(this._pathFor(id, extension), bytes);
  }

  async get(id: string): Promise<StoredAsset | null> {
    // Ids are hex digests; anything else cannot address a file here.
    if (!/^[0-9a-f]{8,64}$/.test(id)) {
      return null;
    }

    for (const [extension, mimeType] of Object.entries(MIME_BY_EXTENSION)) {
      const path = this._pathFor(id, extension);

      if (existsSync(path)) {
        return { id, mimeType, bytes: new Uint8Array(await readFile(path)) };
      }
    }

    return null;
  }

  urlFor(id: string): string {
    return `/ithinq/generated/${id}`;
  }
}

export const devAssetStore = new FileSystemAssetStore();
