import { createHash, createHmac } from 'node:crypto';
import { AssetStoreError, isAssetId, type AssetStore, type StoredAsset } from './asset-store';

/**
 * S3-compatible durable storage for generated media.
 *
 * This is the production implementation of the seam `asset-store.ts` describes.
 * It speaks the S3 REST API directly with SigV4 signed by `node:crypto`, so the
 * renderer gains no SDK dependency for two verbs — the same reasoning that
 * keeps `OpenAIImageGenerator` on plain `fetch`.
 *
 * Path-style addressing (`<endpoint>/<bucket>/<key>`) rather than
 * virtual-hosted, because it is the form every S3-compatible provider accepts:
 * R2, S3 itself, Backblaze B2 and MinIO all work unchanged.
 *
 * `urlFor` still returns a renderer path, never a bucket URL or a presigned
 * one. Generated bytes keep being delivered by `/ithinq/generated/$id` from the
 * renderer's own origin, so the media trust boundary is unchanged by making
 * storage durable: no third-party media host becomes authorised, and a CTA
 * destination can still never be confused with an image source.
 */
export interface S3AssetStoreOptions {
  /** Origin only, e.g. `https://<account>.r2.cloudflarestorage.com`. */
  endpoint: string;
  bucket: string;

  /** `auto` for R2; a real region for S3. */
  region: string;
  accessKeyId: string;
  secretAccessKey: string;

  /** Key prefix inside the bucket. Trailing slash optional. */
  prefix?: string;
  fetchImpl?: typeof fetch;
  timeoutMs?: number;
  now?: () => Date;
}

const EMPTY_PAYLOAD_SHA256 = createHash('sha256').update('').digest('hex');

/** AWS unreserved set is `A-Za-z0-9-_.~`; encodeURIComponent leaves five more. */
function uriEncode(value: string): string {
  return encodeURIComponent(value).replace(/[!'()*]/g, (char) => `%${char.charCodeAt(0).toString(16).toUpperCase()}`);
}

function sha256Hex(value: string | Uint8Array): string {
  return createHash('sha256').update(value).digest('hex');
}

/** `2026-08-31T23:59:59.123Z` -> `20260831T235959Z`. */
export function amzDate(date: Date): string {
  return date
    .toISOString()
    .replace(/[-:]/g, '')
    .replace(/\.\d{3}/, '');
}

export class S3AssetStore implements AssetStore {
  private readonly _origin: string;
  private readonly _bucket: string;
  private readonly _region: string;
  private readonly _accessKeyId: string;
  private readonly _secretAccessKey: string;
  private readonly _prefix: string[];
  private readonly _fetch: typeof fetch;
  private readonly _timeoutMs: number;
  private readonly _now: () => Date;

  constructor(options: S3AssetStoreOptions) {
    const endpoint = new URL(options.endpoint);

    if (endpoint.protocol !== 'https:') {
      /*
       * Credentials ride in an Authorization header on every request. Over
       * plain HTTP they are readable in transit, so this refuses rather than
       * quietly signing into the clear.
       */
      throw new AssetStoreError('Asset store endpoint must be https.', 'insecure_endpoint');
    }

    this._origin = endpoint.origin;
    this._bucket = options.bucket;
    this._region = options.region;
    this._accessKeyId = options.accessKeyId;
    this._secretAccessKey = options.secretAccessKey;
    this._prefix = (options.prefix ?? '').split('/').filter(Boolean);
    this._fetch = options.fetchImpl ?? fetch;
    this._timeoutMs = options.timeoutMs ?? 30_000;
    this._now = options.now ?? (() => new Date());
  }

  /** Canonical, URI-encoded path. Encoding here is what SigV4 signs. */
  private _canonicalPath(id: string): string {
    return `/${[this._bucket, ...this._prefix, id].map(uriEncode).join('/')}`;
  }

  private _authorization(
    method: string,
    canonicalPath: string,
    headers: Record<string, string>,
    payloadHash: string,
    date: Date,
  ): string {
    const stamp = amzDate(date);
    const day = stamp.slice(0, 8);
    const scope = `${day}/${this._region}/s3/aws4_request`;

    const names = Object.keys(headers)
      .map((name) => name.toLowerCase())
      .sort();
    const lookup = new Map(Object.entries(headers).map(([name, value]) => [name.toLowerCase(), value]));
    const canonicalHeaders = names.map((name) => `${name}:${(lookup.get(name) ?? '').trim()}\n`).join('');
    const signedHeaders = names.join(';');

    // The empty line is the canonical query string; these requests carry none.
    const canonicalRequest = [method, canonicalPath, '', canonicalHeaders, signedHeaders, payloadHash].join('\n');
    const stringToSign = ['AWS4-HMAC-SHA256', stamp, scope, sha256Hex(canonicalRequest)].join('\n');

    let key = createHmac('sha256', `AWS4${this._secretAccessKey}`).update(day).digest();
    key = createHmac('sha256', key).update(this._region).digest();
    key = createHmac('sha256', key).update('s3').digest();
    key = createHmac('sha256', key).update('aws4_request').digest();

    const signature = createHmac('sha256', key).update(stringToSign).digest('hex');

    return `AWS4-HMAC-SHA256 Credential=${this._accessKeyId}/${scope}, SignedHeaders=${signedHeaders}, Signature=${signature}`;
  }

  private async _send(
    method: 'GET' | 'PUT',
    id: string,
    body?: Uint8Array,
    mimeType?: string,
  ): Promise<{ response: Response }> {
    const canonicalPath = this._canonicalPath(id);
    const date = this._now();
    const payloadHash = body ? sha256Hex(body) : EMPTY_PAYLOAD_SHA256;

    const headers: Record<string, string> = {
      host: new URL(this._origin).host,
      'x-amz-content-sha256': payloadHash,
      'x-amz-date': amzDate(date),
    };

    if (method === 'PUT' && mimeType) {
      headers['content-type'] = mimeType;

      /*
       * Belt and braces. A gateway that rewrites Content-Type on the way back
       * would otherwise cost us the media type, and `/ithinq/generated/$id`
       * sends `nosniff` — a wrong type there is a blank image, not a guess.
       */
      headers['x-amz-meta-mimetype'] = mimeType;
    }

    const authorization = this._authorization(method, canonicalPath, headers, payloadHash, date);
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), this._timeoutMs);

    try {
      const response = await this._fetch(`${this._origin}${canonicalPath}`, {
        method,
        headers: { ...headers, authorization },
        body: body as BodyInit | undefined,
        signal: controller.signal,

        // Following a redirect would replay the Authorization header elsewhere.
        redirect: 'manual',
      });

      return { response };
    } catch (error) {
      throw new AssetStoreError(
        `Asset store ${method} failed: ${error instanceof Error ? error.message : 'network error'}`,
        'network_error',
      );
    } finally {
      clearTimeout(timer);
    }
  }

  async put(id: string, mimeType: string, bytes: Uint8Array): Promise<void> {
    if (!isAssetId(id)) {
      throw new AssetStoreError('Refusing to store an asset under a non-content-addressed id.', 'invalid_id');
    }

    const { response } = await this._send('PUT', id, bytes, mimeType);

    if (!response.ok) {
      throw new AssetStoreError(`Asset store rejected the write (HTTP ${response.status}).`, 'write_rejected');
    }
  }

  async get(id: string): Promise<StoredAsset | null> {
    // Ids are hex digests; anything else cannot address an object here.
    if (!isAssetId(id)) {
      return null;
    }

    const { response } = await this._send('GET', id);

    if (response.status === 404) {
      return null;
    }

    if (!response.ok) {
      /*
       * Deliberately not treated as a miss. A miss makes the caller regenerate
       * and re-store, so a credential or permission fault would surface only as
       * a quietly repeated image bill; a throw is recorded as a campaign
       * failure the reviewer can actually see.
       */
      throw new AssetStoreError(`Asset store rejected the read (HTTP ${response.status}).`, 'read_rejected');
    }

    const mimeType =
      response.headers.get('content-type') ?? response.headers.get('x-amz-meta-mimetype') ?? 'application/octet-stream';

    return { id, mimeType, bytes: new Uint8Array(await response.arrayBuffer()) };
  }

  urlFor(id: string): string {
    return `/ithinq/generated/${id}`;
  }
}
